Repository mainsail-crew/mainsail, pull requests merged in 2024-07, with the labels that each got.

#1926 fix(gcodeviewer): update gcodeviewer to fix rendering issues
  package-lock.json
  package.json
Labels: size:XS, lgtm

#1920 fix(screwsTiltCalculate): use the same direction on retry
  src/components/dialogs/TheScrewsTiltAdjustDialog.vue
Labels: size:S, lgtm

#1923 refactor: refactor TheTopbar, remove unused gette, fix snackbar
  src/components/TheTopbar.vue
Labels: size:XS, lgtm

#1925 fix(updateManager): fix updatr for git_repos without semver
  src/components/panels/Machine/UpdatePanel/Entry.vue
Labels: size:M, lgtm

#1859 feat: add support for build-in themes and add a Klipper theme
  public/config.json
  public/img/themes/sidebarLogo-klipper.svg
  src/App.vue
  src/components/TheTopbar.vue
  src/components/mixins/theme.ts
  src/components/settings/SettingsUiSettingsTab.vue
  src/locales/en.json
  src/main.ts
  src/store/gui/getters.ts
  src/store/gui/index.ts
  src/store/gui/types.ts
  src/store/types.ts
  src/store/variables.ts
Labels: size:L, lgtm

#1919 feat(notification): add TMC overheating warnings
  src/locales/en.json
  src/store/gui/notifications/getters.ts
Labels: size:M, lgtm

#1929 locale(en): remove unused keys in english locale
  src/locales/en.json
Labels: size:XS, lgtm

#1930 feat(theme): add voron build-in theme
  public/img/themes/sidebarLogo-voron.svg
  src/store/variables.ts
Labels: size:XS, lgtm

#1928 locale(de): update german locale
  src/locales/de.json
Labels: size:S, lgtm

#1933 fix(theme): fix color change on theme change
  src/components/settings/SettingsUiSettingsTab.vue
Labels: size:S, lgtm

#1932 feat(theme): add LDO Motion theme
  public/img/themes/sidebarLogo-ldo.svg
  src/store/variables.ts
Labels: size:XS, lgtm

#1936 feat(theme): add YUMI theme
  public/img/themes/sidebarLogo-yumi.svg
  src/store/variables.ts
Labels: size:XS, lgtm

#1937 feat(theme): add VzBot theme
  public/img/themes/sidebarBackground-vzbot.png
  public/img/themes/sidebarLogo-vzbot.svg
  src/store/variables.ts
Labels: size:XS, lgtm

#1935 feat(theme): add Prusa Research theme
  public/img/themes/sidebarLogo-prusa.svg
  src/store/variables.ts
Labels: size:XS, lgtm

#1931 feat(theme): add bigtreetech theme
  public/img/themes/sidebarLogo-btt.svg
  src/store/variables.ts
Labels: size:XS, lgtm

#1934 feat(theme): add Multec theme
  public/img/themes/sidebarLogo-multec.svg
  src/store/variables.ts
Labels: size:XS, lgtm

#1940 fix(history): add missing fields in detail dialog
  src/components/dialogs/HistoryListPanelDetailsDialog.vue
  src/locales/de.json
  src/locales/en.json
Labels: size:M, lgtm

#1941 fix(maintenance): fix filament trigger for maintenance entries
  src/store/gui/maintenance/getters.ts
Labels: size:XS, lgtm

#1949 perf: fix hang when leaving G-Code Preview page
  src/store/gcodeviewer/mutations.ts
Labels: size:XS, lgtm

#1951 locale(zh): update chinese locale
  src/locales/zh.json
Labels: size:S, lgtm

#1954 fix(gcodeviewer): fix gcodeviewer simulation while printing
  src/components/gcodeviewer/Viewer.vue
Labels: size:M, lgtm

#1958 feat(theme): add option for dedicated CSS file per theme
  public/css/themes/vzbot.css
  src/App.vue
  src/components/mixins/theme.ts
  src/store/types.ts
  src/store/variables.ts
Labels: size:M, lgtm
