Repository mainsail-crew/mainsail, pull requests merged in 2024-12, with the labels that each got.

#2060 fix: fix save z offset in toolhead panel
  src/components/mixins/zoffset.ts
Labels: size:S, lgtm

#2029 feat: add option to hide other Klipper & Moonraker instances
  src/assets/styles/utils.css
  src/components/TheTopCornerMenu.vue
  src/components/dialogs/ConfirmationDialog.vue
  src/components/mixins/services.ts
  src/components/settings/SettingsUiSettingsTab.vue
  src/components/ui/TopCornerMenuService.vue
  src/locales/en.json
  src/store/gui/index.ts
  src/store/gui/types.ts
  src/store/server/types.ts
Labels: size:L, lgtm

#2053 feat(Webcam): add a optional overlay for IDEX calibration
  src/assets/styles/page.css
  src/components/panels/ToolheadControls/CrossControl.vue
  src/components/settings/Webcams/WebcamForm.vue
  src/components/webcams/WebcamNozzleCrosshair.vue
  src/components/webcams/streamers/Mjpegstreamer.vue
  src/components/webcams/streamers/MjpegstreamerAdaptive.vue
  src/components/webcams/streamers/WebrtcCameraStreamer.vue
  src/locales/en.json
  src/store/gui/webcams/types.ts
Labels: size:L, lgtm

#2045 fix: keep macro prompt open for events older than 100
  src/components/dialogs/TheMacroPrompt.vue
Labels: size:M, lgtm

#2043 feat: use _CLIENT_LINEAR_MOVE macros instead of multi-line gcodes
  src/components/mixins/control.ts
  src/components/panels/Extruder/ExtruderControlPanelControl.vue
  src/components/panels/ToolheadControls/MoveToControl.vue
Labels: size:L, lgtm

#2061 refactor: refactor gcodeviewer page
  package-lock.json
  package.json
  src/components/gcodeviewer/Viewer.vue
Labels: size:L, lgtm

#2065 fix: escape all file URLs to support all kind of special chars
  src/components/gcodeviewer/Viewer.vue
  src/components/panels/GcodefilesPanel.vue
  src/components/panels/History/HistoryListEntryJob.vue
  src/components/panels/Machine/ConfigFilesPanel.vue
  src/components/panels/Status/GcodefilesEntry.vue
  src/components/panels/Status/HistoryEntry.vue
  src/components/panels/Status/PrintstatusThumbnail.vue
  src/components/panels/Timelapse/TimelapseFilesPanel.vue
  src/plugins/helpers.ts
  src/store/editor/actions.ts
  src/store/files/getters.ts
  src/store/server/jobQueue/getters.ts
Labels: size:M, lgtm

#2069 fix(Webcam): add ICE check to support older CS versions
  src/components/webcams/streamers/WebrtcCameraStreamer.vue
Labels: size:XS, lgtm

#2070 locale(de): update german locale
  src/locales/de.json
Labels: size:M, lgtm

#2071 fix: fix interface settings Control-Tab when printer is not available
  src/components/mixins/zoffset.ts
  src/components/settings/SettingsControlTab.vue
Labels: size:M, lgtm

#2074 fix: fix print start from dashboard for subdirectory files
  src/components/panels/Status/GcodefilesEntry.vue
Labels: size:XS, lgtm

#2076 fix(macro-prompts): preserve outer quotes
  src/components/dialogs/TheMacroPrompt.vue
Labels: size:XS, lgtm

#2079 fix(Editor): fix maximal height of the sidebar
  src/components/TheEditor.vue
Labels: size:XS, lgtm

#2081 locale(zh): update chinese locale
  src/locales/zh.json
Labels: size:L, lgtm

#2075 fix: hide horizontal scrollbar in StartPrintDialog.vue
  src/components/dialogs/StartPrintDialog.vue
Labels: size:XS, lgtm

#2080 fix(Editor): fix docs link for Kalico
  src/components/TheEditor.vue
  src/components/mixins/base.ts
  src/store/types.ts
  src/store/variables.ts
Labels: size:M, lgtm

#2078 fix: fix z_tilt button for z_tilt_ng with Kalico
  src/components/mixins/control.ts
  src/store/printer/getters.ts
Labels: size:S, lgtm

#2088 fix(Tools): use gcode commands instead of config gcode macros
  src/components/mixins/control.ts
  src/components/panels/Extruder/ExtruderControlPanelTools.vue
  src/components/panels/Extruder/ExtruderControlPanelToolsItem.vue
  src/store/printer/types.ts
Labels: size:M, lgtm
