Repository mainsail-crew/mainsail, pull requests merged in 2024-09, with the labels that each got.

#1989 refactor(ExtruderPanel): add `_` prefix to gcode_state name
  src/components/panels/Extruder/ExtruderControlPanelControl.vue
Labels: size:S, lgtm

#1943 feat: adds a file structure sidebar in the editor
  src/components/TheEditor.vue
  src/components/inputs/Codemirror.vue
  src/locales/en.json
  src/locales/zh.json
  src/store/files/types.ts
Labels: size:L, lgtm

#1996 feat: add output on connection dialog for unauthorized
  src/components/TheConnectingDialog.vue
  src/locales/en.json
  src/plugins/webSocketClient.ts
  src/store/socket/actions.ts
  src/store/socket/index.ts
  src/store/socket/mutations.ts
  src/store/socket/types.ts
Labels: size:M, lgtm

#1994 refactor(webcam): refactor Mjpegstreamer-Adaptive Webcam mode
  src/components/webcams/streamers/MjpegstreamerAdaptive.vue
  src/locales/en.json
Labels: size:L, lgtm

#1992 fix: change Min Cruise Ratio to percent in MachineSettingsPanel
  src/components/panels/MachineSettings/MachineSettingsPanel.vue
  src/components/panels/MachineSettings/MotionSettings.vue
  src/components/panels/MachineSettingsPanel.vue
  src/pages/Dashboard.vue
Labels: size:L, lgtm

#1987 fix(webcam): fix memory leak in MJPEGStreamer client
  src/components/webcams/WebcamWrapperItem.vue
  src/components/webcams/streamers/Mjpegstreamer.vue
  src/locales/en.json
Labels: size:L, lgtm

#2000 fix: correct github commit after link in commit list
  src/components/panels/Machine/UpdatePanel/GitCommitsList.vue
Labels: size:XS, lgtm

#2003 feat: add heartbeat to the moonraker websocket
  src/plugins/webSocketClient.ts
Labels: size:S, lgtm

#2002 fix(ExtruderPanel): fix extrude and speed factor output
  src/components/panels/Extruder/EstimatedExtrusionOutput.vue
Labels: size:S, lgtm

#2012 fix(Editor): Trigger gotoLine only when change is from sidebar
  src/components/TheEditor.vue
Labels: size:S, lgtm

#2010 fix(HistoryPanel): Fix History thumbnails of files in folders
  src/components/panels/History/HistoryListEntryJob.vue
Labels: size:M, lgtm

#1981 fix(webcam): fix some connection issues in Camera-Streamer
  src/components/webcams/WebcamWrapperItem.vue
  src/components/webcams/streamers/WebrtcCameraStreamer.vue
Labels: size:L, lgtm

#2014 fix(Editor): fix editor width when sidebar is hidden
  src/components/TheEditor.vue
Labels: size:XS

#2004 chore(websocket): add function to send and wait for response
  src/plugins/webSocketClient.ts
  src/store/server/actions.ts
Labels: size:M, lgtm

#2018 fix(History): adjust button tooltips to consistent style
  src/components/panels/HistoryListPanel.vue
  src/locales/en.json
Labels: size:M, lgtm

#2006 feat(Heightmap): add option to set the default orientation
  src/components/charts/HeightmapChart.vue
  src/components/settings/SettingsHeightmapTab.vue
  src/locales/en.json
  src/store/gui/heightmap/index.ts
  src/store/gui/heightmap/types.ts
Labels: size:M, lgtm
