Repository mainsail-crew/mainsail, pull requests merged in 2024-08, with the labels that each got.

#1959 feat(updateManager): use info_tag desc for the name
  src/components/panels/Machine/UpdatePanel/Entry.vue
Labels: size:XS, lgtm

#1962 fix(console): trim output to remove spaces at first char
  src/plugins/helpers.ts
Labels: size:XS, lgtm

#1952 locale: Translations update from Hosted Weblate
  src/locales/da.json
  src/locales/de.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hu.json
  src/locales/nl.json
  src/locales/uk.json
  src/locales/zh_TW.json
Labels: size:XL, lgtm

#1968 fix: fix uuid request in MediaMTX webcam client
  src/components/webcams/streamers/WebrtcMediaMTX.vue
Labels: size:M, lgtm

#1973 feat(console): add debug prefix
  src/components/console/ConsoleTableEntry.vue
  src/plugins/helpers.ts
  src/store/server/actions.ts
  src/store/server/mutations.ts
Labels: size:S, lgtm

#1979 fix(MediaMTX): fix some connection issues
  src/components/panels/WebcamPanel.vue
  src/components/settings/Webcams/WebcamForm.vue
  src/components/webcams/WebcamWrapper.vue
  src/components/webcams/WebcamWrapperItem.vue
  src/components/webcams/streamers/WebrtcMediaMTX.vue
  src/pages/Webcam.vue
Labels: size:L, lgtm

#1976 chore(prettier): add support to sort locale json files
  .prettierrc
  package-lock.json
  package.json
  src/components/panels/Status/ExcludeObjectDialogMap.vue
  src/locales/da.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/it.json
  src/locales/pl.json
  src/locales/ru.json
  src/locales/se.json
Labels: size:S, lgtm

#1975 feat(console): add option for RAW-output (for debugging)
  src/components/console/ConsoleTableEntry.vue
  src/components/panels/MiniconsolePanel.vue
  src/locales/en.json
  src/pages/Console.vue
  src/store/gui/console/index.ts
  src/store/gui/console/types.ts
Labels: size:M, lgtm

#1965 fix(ExtruderPanel): restore mode after extruding/retracting
  src/components/panels/Extruder/ExtruderControlPanelControl.vue
Labels: size:S, lgtm

#1982 refactor(timelapse): refactor the timelapse status panel
  src/components/dialogs/TimelapseRenderingsettingsDialog.vue
  src/components/mixins/timelapse.ts
  src/components/panels/Timelapse/TimelapseStatusPanel.vue
Labels: size:XL, lgtm
