Repository mainsail-crew/mainsail, pull requests merged in 2024-05, with the labels that each got.

#1870 fix: calc multiplicator for set_pin gcode
  src/components/inputs/MiscellaneousSlider.vue
Labels: size:XS, lgtm

#1871 fix(maintenance): fix overdue check from printtime based entries
  src/store/gui/maintenance/getters.ts
Labels: size:XS, lgtm

#1885 locale(uk): update ukrainian locale
  src/locales/uk.json
Labels: size:M, lgtm

#1877 locale(zh): update chinese locale
  src/locales/zh.json
Labels: size:M, lgtm

#1884 feat(history): add support for Moonraker sensor history_fields
  src/components/dialogs/HistoryDetailsDialog.vue
  src/components/dialogs/HistoryListPanelDetailsDialog.vue
  src/components/panels/History/HistoryListEntryJob.vue
  src/components/panels/History/HistoryListRow.vue
  src/components/panels/History/HistoryListRowCell.vue
  src/components/panels/HistoryListPanel.vue
  src/store/server/history/types.ts
  src/store/server/index.ts
  src/store/server/sensor/actions.ts
  src/store/server/sensor/getters.ts
  src/store/server/sensor/index.ts
  src/store/server/sensor/mutations.ts
  src/store/server/sensor/types.ts
  src/store/socket/actions.ts
  src/store/variables.ts
Labels: size:XL, lgtm

#1886 feat(history): add moonraker sensors to total statistic
  src/components/mixins/history.ts
  src/components/panels/HistoryListPanel.vue
  src/components/panels/HistoryStatisticsPanel.vue
  src/store/server/history/actions.ts
  src/store/server/history/index.ts
  src/store/server/history/mutations.ts
  src/store/server/history/types.ts
Labels: size:L, lgtm
