Repository mainsail-crew/mainsail, pull requests merged in 2024-06, with the labels that each got.

#1896 fix: consecutive and leading whitespace is not shown in console
  src/components/console/ConsoleTableEntry.vue
Labels: size:XS, lgtm

#1901 fix(webcam): fix fps output in light mode
  src/components/webcams/streamers/Mjpegstreamer.vue
  src/components/webcams/streamers/MjpegstreamerAdaptive.vue
Labels: size:XS, lgtm

#1894 fix: fix duration format function
  src/components/panels/Status/PrintstatusPrinting.vue
Labels: size:XS, lgtm

#1889 refactor(macros): refactor gcode_macros getter
  src/store/printer/getters.ts
Labels: size:S, lgtm

#1873 feat: add support for base url
  src/main.ts
  src/plugins/router.ts
Labels: size:S, lgtm

#1888 feat(dashboard): add support for moonraker sensor
  src/components/panels/Miscellaneous/MoonrakerSensor.vue
  src/components/panels/Miscellaneous/MoonrakerSensorValue.vue
  src/components/panels/MiscellaneousPanel.vue
  src/store/server/sensor/getters.ts
  src/store/server/sensor/mutations.ts
Labels: size:L, lgtm

#1909 fix: update moonraker log path in TheConnectingDialog.vue
  src/components/TheConnectingDialog.vue
Labels: size:XS, lgtm

#1906 feat(systemLoads): add function to output app name in system loads panel
  src/store/printer/actions.ts
  src/store/server/getters.ts
Labels: size:XS, lgtm

#1907 fix(systemLoads): fix temp output when no temp sensor was found in klipper
  src/components/panels/Machine/SystemPanelHost.vue
  src/store/server/getters.ts
Labels: size:XS, lgtm

#1876 fix: display "pause on layer"-button only when the macros exists
  src/components/panels/StatusPanel.vue
Labels: size:XS, lgtm

#1903 fix(tempchart): fix select/unselect monitor sensors in tempchart
  package-lock.json
  package.json
  src/components/charts/TempChart.vue
  src/store/printer/tempHistory/getters.ts
Labels: size:S, lgtm

#1918 fix(macroPromts): fix internal close function
  src/components/dialogs/TheMacroPrompt.vue
Labels: size:S, lgtm

#1913 fix(extruderPanel): add speed_factor to estimate extrusion calc
  src/components/panels/Extruder/EstimatedExtrusionOutput.vue
Labels: size:M, lgtm

#1912 fix(statusPanel): fix the thumbnail overlay in the light theme
  src/components/panels/Status/PrintstatusThumbnail.vue
Labels: size:S, lgtm

#1911 feat(systemLoads): add firmware name, when it is not Klipper
  src/store/printer/getters.ts
Labels: size:XS, lgtm

#1905 feat(statusPanel): add option to disable the thumbnail zoom
  src/components/panels/Status/PrintstatusThumbnail.vue
  src/components/settings/SettingsUiSettingsTab.vue
  src/locales/en.json
  src/store/gui/index.ts
  src/store/gui/types.ts
Labels: size:L, lgtm

#1902 feat: Add hotkeys tied to Save, Save + Restart
  src/components/TheEditor.vue
Labels: size:XS, lgtm
