Repository mainsail-crew/mainsail, pull requests merged in 2024-11, with the labels that each got.

#2019 fix(Webcam): capitalize the connection state
  src/components/webcams/streamers/WebrtcCameraStreamer.vue
  src/components/webcams/streamers/WebrtcMediaMTX.vue
Labels: size:S, lgtm

#1988 refactor(ControlPanel): use SAVE/RESTORE STATE when moving
  src/components/mixins/control.ts
Labels: size:XS, lgtm

#1953 fix(control): check set actionButton before display it
  src/components/mixins/control.ts
  src/components/panels/ToolheadControls/CircleControl.vue
  src/components/panels/ToolheadControls/CrossControl.vue
Labels: size:S, lgtm

#2020 fix: fix image viewer if the image is wider than the viewport
  src/components/panels/Machine/ConfigFilesPanel.vue
Labels: size:XS, lgtm

#2033 feat(Console): Change from Helplist to Printer.Gcode
  src/components/console/CommandHelpModal.vue
  src/components/console/CommandHelpModalEntry.vue
  src/components/console/ConsoleTable.vue
  src/components/inputs/ConsoleTextarea.vue
  src/components/mixins/console.ts
  src/components/panels/MiniconsolePanel.vue
  src/locales/en.json
  src/pages/Console.vue
  src/plugins/webSocketClient.ts
  src/store/printer/actions.ts
  src/store/printer/mutations.ts
  src/store/printer/types.ts
  src/store/server/actions.ts
Labels: size:L, lgtm

#2028 fix: fix color picker for PCA9632
  src/store/printer/getters.ts
Labels: size:XS, lgtm

#1956 fix(notifications): fix dismiss function for tmc warnings
  src/store/gui/notifications/getters.ts
Labels: size:S, lgtm

#2007 feat(History): add option to show stats in different values
  src/components/charts/HistoryAllPrintStatusChart.vue
  src/components/charts/HistoryAllPrintStatusTable.vue
  src/components/charts/HistoryAllPrintStatusTableItem.vue
  src/components/mixins/historyStats.ts
  src/components/panels/HistoryListPanel.vue
  src/components/panels/HistoryStatisticsPanel.vue
  src/locales/en.json
  src/store/server/history/getters.ts
  src/store/server/history/types.ts
Labels: size:L, lgtm

#1939 feat: multiple nevermore support
  src/components/panels/Temperature/TemperaturePanelList.vue
  src/components/panels/Temperature/TemperaturePanelListItemEdit.vue
  src/components/panels/Temperature/TemperaturePanelListItemNevermore.vue
Labels: size:M, lgtm

#2041 fix: Tool rows in even lengths, and more visually tidy
  src/components/panels/Extruder/ExtruderControlPanelTools.vue
Labels: size:XS, lgtm

#2049 locale(it): update italian translation
  src/locales/it.json
Labels: size:L, lgtm

#2047 refactor: refactor files list in StatusPanel
  src/components/panels/Status/Gcodefiles.vue
  src/components/panels/Status/GcodefilesEntry.vue
Labels: size:XL, lgtm

#2050 fix: fix reference link in editor while printing
  src/components/TheEditor.vue
Labels: size:XS, lgtm

#2046 feat: add button to open the device dialog in SystemPanel
  src/components/panels/Machine/SystemPanel.vue
Labels: size:M, lgtm

#2040 feat: add SGP40 support
  src/store/variables.ts
Labels: size:XS, lgtm

#2054 feat(StatusPanel): change tab text to icons
  src/components/panels/StatusPanel.vue
  src/locales/de.json
  src/locales/en.json
Labels: size:M, lgtm

#2055 feat(StatusPanel): add option to show history in StatusPanel
  src/components/panels/Status/History.vue
  src/components/panels/Status/HistoryEntry.vue
  src/components/panels/StatusPanel.vue
  src/components/settings/SettingsUiSettingsTab.vue
  src/locales/en.json
  src/store/gui/index.ts
  src/store/gui/types.ts
  src/store/server/history/types.ts
Labels: size:L, lgtm

#2057 fix(Webcam): make webcam view non-draggable
  src/components/webcams/streamers/Mjpegstreamer.vue
  src/components/webcams/streamers/MjpegstreamerAdaptive.vue
  src/components/webcams/streamers/Uv4lMjpeg.vue
Labels: size:XS, lgtm
