Repository mainsail-crew/mainsail, pull requests merged in 2024-10, with the labels that each got.

#2031 refactor: refactor Console & MiniConsole
  src/components/inputs/ConsoleTextarea.vue
  src/components/mixins/console.ts
  src/components/panels/MiniconsolePanel.vue
  src/pages/Console.vue
  src/store/gui/console/mutations.ts
Labels: size:XL, lgtm

#2035 feat: Add link to the Docs for Unauthorized connections
  src/components/TheConnectingDialog.vue
  src/locales/de.json
  src/locales/en.json
Labels: size:S, lgtm

#2030 chore(Docker): Enable ipv6 in nginx.conf
  .docker/nginx.conf
Labels: size:XS, lgtm
