Repository mainsail-crew/mainsail, pull requests merged in 2025-06, with the labels that each got.

#2210 feat: Added more date format options
  src/components/mixins/base.ts
  src/components/settings/SettingsGeneralTab.vue
Labels: size:L, lgtm

#2227 fix(gcodeviewer): fix scarf seams in Gcodeviewer
  package-lock.json
  package.json
Labels: size:XS, lgtm

#2226 fix(Files): fix disk usage in new directories
  src/store/files/actions.ts
  src/store/files/getters.ts
Labels: size:S, lgtm
