Repository mainsail-crew/mainsail, pull requests merged in 2025-04, with the labels that each got.

#2168 chore: update dependencies in package.json
  cypress.config.ts
  cypress/plugins/index.js
  package-lock.json
  package.json
  src/components/inputs/MiscellaneousLight.vue
  src/components/settings/SettingsGeneralTab.vue
  src/locales/es.json
  src/locales/ru.json
  src/locales/uk.json
  src/main.ts
  src/plugins/i18n.ts
  src/plugins/vuetify.ts
  src/store/gui/getters.ts
  tsconfig.json
  vite.config.ts
Labels: size:L, lgtm

#2172 fix: fix the axios up- & download rate
  src/store/editor/actions.ts
  src/store/editor/index.ts
  src/store/editor/types.ts
Labels: size:M, lgtm

#2124 refactor(Machine): refactor endstop panel and add dockable_probe
  src/components/panels/Machine/EndstopPanel.vue
  src/components/panels/Machine/EndstopPanelItem.vue
Labels: size:L, lgtm

#2160 fix(spoolman): save spool id in lowercase variable
  src/components/dialogs/SpoolmanChangeSpoolDialog.vue
Labels: size:XS, lgtm

#2173 feat: Add load cell gram scales in misc panel
  src/components/panels/Miscellaneous/MiscellaneousSensor.vue
  src/components/panels/Miscellaneous/MoonrakerSensorValue.vue
  src/components/panels/MiscellaneousPanel.vue
  src/plugins/helpers.ts
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: size:L, lgtm

#2193 feat: Add support for hall filament width sensor
  src/components/inputs/FilamentSensor.vue
  src/components/panels/MiscellaneousPanel.vue
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: size:S, lgtm

#2179 fix(python): loose package versions
  src/components/panels/Machine/UpdatePanel.vue
  src/components/panels/Machine/UpdatePanel/Entry.vue
  src/components/panels/Machine/UpdatePanel/UpdateHintAll.vue
Labels: size:S, lgtm

#2191 fix: only git repos can soft recover
  src/components/panels/Machine/UpdatePanel/Entry.vue
Labels: size:XS, lgtm

#2169 ci: fix output of auto-analyze workflow
  .github/workflows/auto-analyze.yml
Labels: size:XS, lgtm

#2182 build(deps): update dependencies in package.json
  package-lock.json
  package.json
Labels: size:XS, lgtm

#2181 chore: remove deprecated @types/cypress package
  package-lock.json
  package.json
Labels: size:XS, lgtm

#2195 ci: use GITHUB_TOKEN in auto-analyze.yml
  .github/workflows/auto-analyze.yml
Labels: size:XS, lgtm

#2194 ci(check-locale): fix issues with i18n-extract workflow
  .github/workflows/check_locale.yml
  .gitignore
  package.json
  vue-i18n-extract.config.js
Labels: size:S, lgtm

#2198 ci(check-locale): fix path to vue-i18n-extract script
  .github/workflows/check_locale.yml
Labels: size:XS, lgtm

#2202 ci(check-locale): fix check-locale workflow
  .github/workflows/check_locale.yml
Labels: size:XS, lgtm

#2141 feat: Add search functionality to macro settings interface
  src/components/settings/SettingsMacrosTabExpert.vue
  src/components/settings/SettingsMacrosTabSimple.vue
  src/locales/cz.json
  src/locales/da.json
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hu.json
  src/locales/it.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/nl.json
  src/locales/pl.json
  src/locales/pt.json
  src/locales/ru.json
  src/locales/se.json
  src/locales/tr.json
  src/locales/uk.json
  src/locales/zh.json
  src/locales/zh_TW.json
Labels: size:L, lgtm

#2129 fix: fix history filter reactivity
  src/components/charts/HistoryAllPrintStatusTable.vue
  src/components/charts/HistoryFilamentUsage.vue
  src/components/charts/HistoryPrinttimeAvg.vue
  src/components/mixins/history.ts
  src/components/mixins/historyStats.ts
  src/components/panels/History/HistoryListPanelExportCsv.vue
  src/components/panels/HistoryListPanel.vue
  src/components/panels/HistoryStatisticsPanel.vue
  src/store/gui/actions.ts
  src/store/server/history/getters.ts
  src/store/server/history/types.ts
Labels: size:L, lgtm
