Repository mainsail-crew/mainsail, pull requests merged in 2025-01, with the labels that each got.

#2025 feat: Add support SHT3X humidity
  src/store/variables.ts
Labels: size:XS, lgtm

#2104 fix(Locale): Add missing translation key in SettingsControlTab
  src/components/settings/SettingsControlTab.vue
  src/locales/en.json
Labels: size:XS, lgtm

#2105 locale(en): remove unused key
  src/locales/en.json
Labels: size:XS, lgtm

#2108 feat(Console): Improve key up/down function in Console textarea
  src/components/inputs/ConsoleTextarea.vue
Labels: size:S, lgtm

#2127 fix: update Gcode-Viewer lib from sindarius to fix G2/G3 visualisation
  package-lock.json
  package.json
Labels: size:XS, lgtm

#2128 locale(ru): update russian locale
  src/locales/ru.json
Labels: size:L, lgtm

#2092 feat(Update): implement python package entries
  src/components/panels/Machine/UpdatePanel/Entry.vue
  src/store/server/updateManager/actions.ts
  src/store/server/updateManager/types.ts
Labels: size:M, lgtm
