Repository mainsail-crew/mainsail, pull requests merged in 2025-08, with the labels that each got.

#2215 chore: update ISSUE_TEMPLATEs zu use the type field
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size:XS, lgtm

#2213 feat: add -unprivileged docker image to conform with restrired pod security standard
  .github/workflows/publish_docker.yml
  Dockerfile
Labels: size:M, lgtm

#2218 refactor(miscellaneous): refactor led/neopixel in MiscellaneousPanel.vue
  src/components/dialogs/MiscellaneousLightNeopixelDialog.vue
  src/components/dialogs/MiscellaneousLightNeopixelDialogPreset.vue
  src/components/inputs/MiscellaneousLight.vue
  src/components/inputs/NumberInput.vue
  src/components/mixins/miscellaneous.ts
  src/components/panels/Miscellaneous/MiscellaneousLight.vue
  src/components/panels/Miscellaneous/MiscellaneousLightNeopixel.vue
  src/components/panels/Miscellaneous/MiscellaneousLightNeopixelGroup.vue
  src/components/panels/Miscellaneous/MiscellaneousLightNeopixelState.vue
  src/components/panels/MiscellaneousPanel.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabLightGroups.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabLightGroupsForm.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabLightGroupsList.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabLightGroupsListEntry.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabLightPresets.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabLightPresetsForm.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabLightPresetsList.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabLightPresetsListEntry.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabList.vue
  src/components/settings/Miscellaneous/SettingsMiscellaneousTabListLight.vue
  src/components/settings/SettingsMiscellaneousTab.vue
  src/components/settings/SettingsMiscellaneousTabLightGroups.vue
  src/components/settings/SettingsMiscellaneousTabLightPresets.vue
  src/locales/en.json
  src/store/gui/miscellaneous/actions.ts
  src/store/gui/miscellaneous/getters.ts
  src/store/gui/miscellaneous/mutations.ts
  src/store/printer/getters.ts
Labels: size:XXL, lgtm
